name: On Push

on:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  Update_GH_Pages:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“© Fetching Repository
        uses: actions/checkout@v2
      - name: ğŸ’½ Installing Composer
        uses: nanasess/composer-installer-action@master
      - name: âš’ï¸Setting Up Envato API
        run: |
          cd scripts/envato-api && composer install --no-dev
          php app.php ${{ secrets.ENVATO_TOKEN }}
      - name: âš’ï¸Setting Up WordPress.org API
        run: |
          cd scripts/wordpress-org-api && composer install --no-dev
          php app.php
      - name: ğŸš€ Publishing To Github
        run: |
          git config --global user.email "githubactionbot+envato@gmail.com" && git config --global user.name "Envato Items Updated !"
          if [ "$(git status ./envato/ --porcelain)" != "" ]; then
            echo "ğŸ‘Œ Envato Items JSON Updated"
            git add ./envato/.
            git commit -m "ğŸ“– #$GITHUB_RUN_NUMBER - Envato Items Data Updated / âš¡ Triggered By $GITHUB_SHA"
            git push origin
          else
            echo "âœ… Envato Items : Nothing To Push"
          fi

          git config --global user.email "githubactionbot+wp@gmail.com" && git config --global user.name "WordPress Plugins Updated !"
          if [ "$(git status ./wordpress.org/ --porcelain)" != "" ]; then
            echo "ğŸ‘Œ WordPress.org Plugins JSON Updated"
            git add ./wordpress.org/.
            git commit -m "ğŸ“– #$GITHUB_RUN_NUMBER - WordPress Plugins Data Updated / âš¡ Triggered By $GITHUB_SHA"
            git push origin
          else
            echo "âœ… Envato Items : Nothing To Push"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
