name: On Push

on:
  schedule:
    - cron: '*/60 * * * *'
  push:
    branches:
      - master

jobs:
  Update_GH_Pages:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“© Fetching Repository
        uses: actions/checkout@v2
      - name: ğŸ’½ Installing Composer
        uses: nanasess/composer-installer-action@master
      - name: âš’ï¸ Setting Up Envato API
        run: |
          cd scripts/envato-api && composer install --no-dev
          php app.php ${{ secrets.ENVATO_TOKEN }}
      - name: ğŸš€ Publishing To Github
        run: |
          git config --global user.email "githubactionbot@gmail.com" && git config --global user.name "Envato Items Updated !"
          if [ "$(git status --porcelain)" != "" ]; then
            echo "ğŸ‘Œ Items JSON Updated"
            git add ./envato/.
            git commit -m "ğŸ“– #$GITHUB_RUN_NUMBER - Envato Items Data Updated / âš¡ Triggered By $GITHUB_SHA"
            git push origin
          else
            echo "âœ… Nothing To Push"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
